services:
  php_test:
    build:
      context: .
    container_name: product-api-php_test
    restart: unless-stopped
    depends_on:
      database_test:
        condition: service_healthy
    volumes:
      - .:/var/www

  database_test:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_test
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data_test:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data_test:
