services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Service\Seed\ProductSeeder:
        arguments:
            $productsSeedFilePath: '%kernel.project_dir%/tests/assets/products.json'

    App\Service\Seed\DiscountSeeder:
        arguments:
            $discountsSeedFilePath: '%kernel.project_dir%/tests/assets/discounts.json'
